version: '3.8'
name: sspd_work1
services:

  db:
    image: mysql:8.0
    container_name: mysql_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: appDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app_network

  web_server:
    build: .
    container_name: php_apache
    ports: 
      - "8000:80"
    restart: always
    depends_on:
      - db
    volumes:
      - ./index.php:/var/www/html/index.php
      - ./style.css:/var/www/html/style.css
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge