services:
  adminpanel:
    build:
      context: .
      dockerfile: Dockerfile
      target: adminpanel
    environment:
      - ADMINPANEL_URL=http://0.0.0.0:8082/
      - ADMINPANEL_TOKEN=changeme
    ports:
      - "8082:8082"
    volumes:
      - adminpanel_logs:/app/logs
    restart: unless-stopped

  drawer:
    build:
      context: .
      dockerfile: Dockerfile
      target: drawer
    environment:
      - DRAWER_URL=http://0.0.0.0:8080/
    ports:
      - "8080:8080"
    volumes:
      - drawer_logs:/app/logs
    restart: unless-stopped

  sorter:
    build:
      context: .
      dockerfile: Dockerfile
      target: sorter
    environment:
      - SORTER_URL=http://0.0.0.0:8081/
    ports:
      - "8081:8081"
    volumes:
      - sorter_logs:/app/logs
    restart: unless-stopped

volumes:
  adminpanel_logs:
  drawer_logs:
  sorter_logs:
